import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"

import { ProductContextProvider } from "./contexts/useProductConext";
import { AuthProvider } from "./contexts/useAuthContext";
import { CartProvider } from "./contexts/useCartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <ProductContextProvider>
          <CartProvider>
        {children}
        </CartProvider>
        </ProductContextProvider></AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
